name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Set up environment variables copy from .env.example
      run: |
        cp .env.example .env
        set -a
        source .env
        set +a

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for Redis to be ready
      run: |
        dockerize -wait tcp://redis:6379 -timeout 1m

    - name: Wait for Backend (Django) to be ready
      run: |
        dockerize -wait http://localhost:8000 -timeout 1m

    - name: Wait for Celery Worker to be ready
      run: |
        dockerize -wait tcp://localhost:5555 -timeout 1m

    - name: Run Tests
      run: |
        python manage.py test
